# .github/workflows/tests.yml
name: test
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install deps
        run: pip install -r requirements.txt
      - name: Install package (src layout)
        run: pip install -e .
      - name: Ruff check
        run: ruff check .
      - name: Run tests
        run: pytest -q
