name: publish

on:
  push:
    tags:
      - "v*"        # ex: v0.2.0  -> PyPI
      - "test/v*"   # ex: test/v0.2.0 -> TestPyPI
  workflow_dispatch:
    inputs:
      repository:
        description: "Cible de publication"
        required: true
        default: "pypi"
        type: choice
        options:
          - pypi
          - testpypi

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install build backend
        run: pip install build

      - name: Build sdist & wheel
        run: python -m build

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/*

  publish:
    needs: build
    runs-on: ubuntu-latest

    # Détermine automatiquement la cible: testpypi si tag "test/v*", sinon pypi
    env:
      TARGET_REPO: ${{ startsWith(github.ref, 'refs/tags/test/v') && 'testpypi' || 'pypi' }}

    # Si lancé à la main, l’input 'repository' prend le dessus
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist

      - name: Choisir la cible (dispatch > tag)
        id: target
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            echo "repo=${{ inputs.repository }}" >> $GITHUB_OUTPUT
          else
            echo "repo=${{ env.TARGET_REPO }}" >> $GITHUB_OUTPUT
          fi

      # Publication via Trusted Publishing (OIDC)
      # TestPyPI
      - name: Publish to TestPyPI
        if: steps.target.outputs.repo == 'testpypi'
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
          # Pas besoin de token si Trusted Publishing activé sur TestPyPI
        permissions:
          id-token: write  # requis pour OIDC

      # PyPI
      - name: Publish to PyPI
        if: steps.target.outputs.repo == 'pypi'
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          # Pas besoin de token si Trusted Publishing activé sur PyPI
        permissions:
          id-token: write  # requis pour OIDC
