# .github/workflows/publish.yml
name: publish

on:
  # Lancement manuel
  workflow_dispatch:
  # Publication automatique quand on pousse un tag v*
  push:
    tags:
      - 'v*'

# IMPORTANT: permissions au niveau racine (pour OIDC)
permissions:
  contents: read
  id-token: write

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    # Optionnel: si tu as créé un Environment nommé "testpypi" côté GitHub
    # enlève cette ligne si tu n'utilises pas d'environment
    environment: testpypi

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install build backend
        run: python -m pip install --upgrade pip build

      - name: Build sdist & wheel
        run: python -m build

      # Publication sur TestPyPI (Trusted Publisher)
      # - en workflow_dispatch
      # - ou sur tag v* (utile pour tester)
      - name: Publish to TestPyPI
        if: github.event_name == 'workflow_dispatch' || startsWith(github.ref, 'refs/tags/v')
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/

      # Publication sur PyPI: seulement pour les tags v* SANS suffixe pré-release
      # (ex: v1.2.3 publie; v1.2.3-rc1 ne publie pas)
      - name: Publish to PyPI
        if: startsWith(github.ref, 'refs/tags/v') && !contains(github.ref, '-rc')
        uses: pypa/gh-action-pypi-publish@release/v1
